# Generated by Django 5.1 on 2024-09-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='core.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ManyToManyField(related_name='address', to='core.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ManyToManyField(to='core.state', verbose_name='state'),
        ),
    ]
